# Generated by Django 4.2.7 on 2024-01-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_employe_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('place', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
